"""updated the student,course and enrolment

Revision ID: 6442e6c62f3b
Revises: 6efe2cc51b28
Create Date: 2025-04-16 22:35:39.345717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6442e6c62f3b'
down_revision = '6efe2cc51b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('enrolled_on',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('enrolled_on',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
